# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      working-directory: ./java-apps
      run: chmod +x mvnw 

    - name: Build with Gradle
      working-directory: ./java-apps
      run: ./mvnw clean install

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ['bank-analysis', 'bank-gateway', 'bank-storage']
        
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: deploy ${{ matrix.application }}
      uses: docker/build-push-action@v2
      with:
        context: ./java-apps/${{ matrix.application }}
        file: ./java-apps/${{ matrix.application }}/Dockerfile
        push: true
        tags: asafino/${{ matrix.application }}:latest