# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: deploy bank-analysis
      id: deploy_bank-analysis
      uses: docker/build-push-action@v2
      with:
        context: ./java-apps/bank-analysis
        file: ./java-apps/bank-analysis/Dockerfile
        push: true
        tags: asafino/bank-analysis:latest

    - name: Image digest
      run: echo ${{ steps.deploy_bank-analysis.outputs.digest }}